// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: clerk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_clerk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Event) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Attribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Attribute_AsString
	//	*Attribute_AsInt64
	//	*Attribute_AsDouble
	//	*Attribute_AsBool
	Value         isAttribute_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_clerk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{1}
}

func (x *Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Attribute) GetValue() isAttribute_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Attribute) GetAsString() string {
	if x != nil {
		if x, ok := x.Value.(*Attribute_AsString); ok {
			return x.AsString
		}
	}
	return ""
}

func (x *Attribute) GetAsInt64() int64 {
	if x != nil {
		if x, ok := x.Value.(*Attribute_AsInt64); ok {
			return x.AsInt64
		}
	}
	return 0
}

func (x *Attribute) GetAsDouble() float64 {
	if x != nil {
		if x, ok := x.Value.(*Attribute_AsDouble); ok {
			return x.AsDouble
		}
	}
	return 0
}

func (x *Attribute) GetAsBool() bool {
	if x != nil {
		if x, ok := x.Value.(*Attribute_AsBool); ok {
			return x.AsBool
		}
	}
	return false
}

type isAttribute_Value interface {
	isAttribute_Value()
}

type Attribute_AsString struct {
	AsString string `protobuf:"bytes,2,opt,name=as_string,json=asString,proto3,oneof"`
}

type Attribute_AsInt64 struct {
	AsInt64 int64 `protobuf:"varint,3,opt,name=as_int64,json=asInt64,proto3,oneof"`
}

type Attribute_AsDouble struct {
	AsDouble float64 `protobuf:"fixed64,4,opt,name=as_double,json=asDouble,proto3,oneof"`
}

type Attribute_AsBool struct {
	AsBool bool `protobuf:"varint,5,opt,name=as_bool,json=asBool,proto3,oneof"`
}

func (*Attribute_AsString) isAttribute_Value() {}

func (*Attribute_AsInt64) isAttribute_Value() {}

func (*Attribute_AsDouble) isAttribute_Value() {}

func (*Attribute_AsBool) isAttribute_Value() {}

type Index struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*Index_Chunk         `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_clerk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{2}
}

func (x *Index) GetChunks() []*Index_Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type Bloom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bloom         []byte                 `protobuf:"bytes,1,opt,name=bloom,proto3" json:"bloom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bloom) Reset() {
	*x = Bloom{}
	mi := &file_clerk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bloom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bloom) ProtoMessage() {}

func (x *Bloom) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bloom.ProtoReflect.Descriptor instead.
func (*Bloom) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{3}
}

func (x *Bloom) GetBloom() []byte {
	if x != nil {
		return x.Bloom
	}
	return nil
}

type CreateEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventsRequest) Reset() {
	*x = CreateEventsRequest{}
	mi := &file_clerk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventsRequest) ProtoMessage() {}

func (x *CreateEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventsRequest.ProtoReflect.Descriptor instead.
func (*CreateEventsRequest) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{4}
}

func (x *CreateEventsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type CreateEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventsResponse) Reset() {
	*x = CreateEventsResponse{}
	mi := &file_clerk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventsResponse) ProtoMessage() {}

func (x *CreateEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventsResponse.ProtoReflect.Descriptor instead.
func (*CreateEventsResponse) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{5}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_clerk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_clerk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type AppendBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendBlockRequest) Reset() {
	*x = AppendBlockRequest{}
	mi := &file_clerk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBlockRequest) ProtoMessage() {}

func (x *AppendBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBlockRequest.ProtoReflect.Descriptor instead.
func (*AppendBlockRequest) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{8}
}

func (x *AppendBlockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AppendBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendBlockResponse) Reset() {
	*x = AppendBlockResponse{}
	mi := &file_clerk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBlockResponse) ProtoMessage() {}

func (x *AppendBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBlockResponse.ProtoReflect.Descriptor instead.
func (*AppendBlockResponse) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{9}
}

type Index_Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           [][]byte               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Mark          *Index_Chunk_Mark      `protobuf:"bytes,2,opt,name=mark,proto3" json:"mark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index_Chunk) Reset() {
	*x = Index_Chunk{}
	mi := &file_clerk_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index_Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index_Chunk) ProtoMessage() {}

func (x *Index_Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index_Chunk.ProtoReflect.Descriptor instead.
func (*Index_Chunk) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Index_Chunk) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *Index_Chunk) GetMark() *Index_Chunk_Mark {
	if x != nil {
		return x.Mark
	}
	return nil
}

type Index_Chunk_Mark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index_Chunk_Mark) Reset() {
	*x = Index_Chunk_Mark{}
	mi := &file_clerk_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index_Chunk_Mark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index_Chunk_Mark) ProtoMessage() {}

func (x *Index_Chunk_Mark) ProtoReflect() protoreflect.Message {
	mi := &file_clerk_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index_Chunk_Mark.ProtoReflect.Descriptor instead.
func (*Index_Chunk_Mark) Descriptor() ([]byte, []int) {
	return file_clerk_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Index_Chunk_Mark) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Index_Chunk_Mark) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_clerk_proto protoreflect.FileDescriptor

const file_clerk_proto_rawDesc = "" +
	"\n" +
	"\vclerk.proto\x12\tscribe.v1\"M\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x124\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2\x14.scribe.v1.AttributeR\n" +
	"attributes\"\x9c\x01\n" +
	"\tAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\tas_string\x18\x02 \x01(\tH\x00R\basString\x12\x1b\n" +
	"\bas_int64\x18\x03 \x01(\x03H\x00R\aasInt64\x12\x1d\n" +
	"\tas_double\x18\x04 \x01(\x01H\x00R\basDouble\x12\x19\n" +
	"\aas_bool\x18\x05 \x01(\bH\x00R\x06asBoolB\a\n" +
	"\x05value\"\xb7\x01\n" +
	"\x05Index\x12.\n" +
	"\x06chunks\x18\x01 \x03(\v2\x16.scribe.v1.Index.ChunkR\x06chunks\x1a~\n" +
	"\x05Chunk\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\fR\x03ids\x12/\n" +
	"\x04mark\x18\x02 \x01(\v2\x1b.scribe.v1.Index.Chunk.MarkR\x04mark\x1a2\n" +
	"\x04Mark\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\x1d\n" +
	"\x05Bloom\x12\x14\n" +
	"\x05bloom\x18\x01 \x01(\fR\x05bloom\"?\n" +
	"\x13CreateEventsRequest\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.scribe.v1.EventR\x06events\"\x16\n" +
	"\x14CreateEventsResponse\"\x1f\n" +
	"\rSearchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"8\n" +
	"\x0eSearchResponse\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x10.scribe.v1.EventR\x05event\"(\n" +
	"\x12AppendBlockRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13AppendBlockResponse2\x9e\x01\n" +
	"\bRecorder\x12Q\n" +
	"\fCreateEvents\x12\x1e.scribe.v1.CreateEventsRequest\x1a\x1f.scribe.v1.CreateEventsResponse\"\x00\x12?\n" +
	"\x06Search\x12\x18.scribe.v1.SearchRequest\x1a\x19.scribe.v1.SearchResponse\"\x002\x9b\x01\n" +
	"\bSearcher\x12N\n" +
	"\vAppendBlock\x12\x1d.scribe.v1.AppendBlockRequest\x1a\x1e.scribe.v1.AppendBlockResponse\"\x00\x12?\n" +
	"\x06Search\x12\x18.scribe.v1.SearchRequest\x1a\x19.scribe.v1.SearchResponse\"\x00B\aZ\x05../pbb\x06proto3"

var (
	file_clerk_proto_rawDescOnce sync.Once
	file_clerk_proto_rawDescData []byte
)

func file_clerk_proto_rawDescGZIP() []byte {
	file_clerk_proto_rawDescOnce.Do(func() {
		file_clerk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clerk_proto_rawDesc), len(file_clerk_proto_rawDesc)))
	})
	return file_clerk_proto_rawDescData
}

var file_clerk_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_clerk_proto_goTypes = []any{
	(*Event)(nil),                // 0: scribe.v1.Event
	(*Attribute)(nil),            // 1: scribe.v1.Attribute
	(*Index)(nil),                // 2: scribe.v1.Index
	(*Bloom)(nil),                // 3: scribe.v1.Bloom
	(*CreateEventsRequest)(nil),  // 4: scribe.v1.CreateEventsRequest
	(*CreateEventsResponse)(nil), // 5: scribe.v1.CreateEventsResponse
	(*SearchRequest)(nil),        // 6: scribe.v1.SearchRequest
	(*SearchResponse)(nil),       // 7: scribe.v1.SearchResponse
	(*AppendBlockRequest)(nil),   // 8: scribe.v1.AppendBlockRequest
	(*AppendBlockResponse)(nil),  // 9: scribe.v1.AppendBlockResponse
	(*Index_Chunk)(nil),          // 10: scribe.v1.Index.Chunk
	(*Index_Chunk_Mark)(nil),     // 11: scribe.v1.Index.Chunk.Mark
}
var file_clerk_proto_depIdxs = []int32{
	1,  // 0: scribe.v1.Event.attributes:type_name -> scribe.v1.Attribute
	10, // 1: scribe.v1.Index.chunks:type_name -> scribe.v1.Index.Chunk
	0,  // 2: scribe.v1.CreateEventsRequest.events:type_name -> scribe.v1.Event
	0,  // 3: scribe.v1.SearchResponse.event:type_name -> scribe.v1.Event
	11, // 4: scribe.v1.Index.Chunk.mark:type_name -> scribe.v1.Index.Chunk.Mark
	4,  // 5: scribe.v1.Recorder.CreateEvents:input_type -> scribe.v1.CreateEventsRequest
	6,  // 6: scribe.v1.Recorder.Search:input_type -> scribe.v1.SearchRequest
	8,  // 7: scribe.v1.Searcher.AppendBlock:input_type -> scribe.v1.AppendBlockRequest
	6,  // 8: scribe.v1.Searcher.Search:input_type -> scribe.v1.SearchRequest
	5,  // 9: scribe.v1.Recorder.CreateEvents:output_type -> scribe.v1.CreateEventsResponse
	7,  // 10: scribe.v1.Recorder.Search:output_type -> scribe.v1.SearchResponse
	9,  // 11: scribe.v1.Searcher.AppendBlock:output_type -> scribe.v1.AppendBlockResponse
	7,  // 12: scribe.v1.Searcher.Search:output_type -> scribe.v1.SearchResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_clerk_proto_init() }
func file_clerk_proto_init() {
	if File_clerk_proto != nil {
		return
	}
	file_clerk_proto_msgTypes[1].OneofWrappers = []any{
		(*Attribute_AsString)(nil),
		(*Attribute_AsInt64)(nil),
		(*Attribute_AsDouble)(nil),
		(*Attribute_AsBool)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clerk_proto_rawDesc), len(file_clerk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_clerk_proto_goTypes,
		DependencyIndexes: file_clerk_proto_depIdxs,
		MessageInfos:      file_clerk_proto_msgTypes,
	}.Build()
	File_clerk_proto = out.File
	file_clerk_proto_goTypes = nil
	file_clerk_proto_depIdxs = nil
}
